export const priceListConst = [
    {
        id: 1,
        title: 'Коврик игровой',
        content: 'Коврик',
        category: 'electronics',
        status: '',
    },
    {
        id: 2,
        title: 'Мышка игровая',
        content: 'Мышка',
        category: 'electronics',
        status: '',
    },
    {
        id: 3,
        title: 'Наушники JBL',
        content: 'Наушники',
        category: 'electronics',
        status: '',
    },
    {
        id: 4,
        title: 'Флешка на 2000 ТБ',
        content: 'Флешка',
        category: 'electronics',
        status: '',
    },
    {
        id: 5,
        title: 'Ковер обыкновенный',
        content: 'Ковер',
        category: 'home',
        status: '',
    },
    {
        id: 6,
        title: 'Песни Сердючки',
        content: 'Выступает лично',
        category: 'concert',
        status: '',
    },
    {
        id: 7,
        title: 'Молоток алмазный',
        content: 'Молоток',
        category: 'tools',
        status: '',
    },
]